### ISSUE TITLE
成就图片格式和命名有限制吗

### ISSUE THREAD

**Issue by actforjason** [Wu-Yijun/steam_client_loader#1]
你好，图片有什么更好的爬取方式吗？

**Comment by Wu-Yijun** [comment]
成就图片的命名应与 achievements.json 中的 "icon" 和 "icon_gray" 对应的键值一致. 使用脚本生成的 achievements.json 中的键值和从SteamDB上下载到的都是图像的MD5哈希值.jpg的形式, 因此可以直接套用. 如果你希望手动修改成就图像名称, 不要忘记也修改对应的 achievements.json 的键值.

---

我新增了一个文件 `download_achievements.py` , 你可以用它一键下载全部图像.


---
或者也可以手动下载:

通过在 SteamDB 上查找到成就列表页面, 通过 Crtl+S 保存此页面, 保存选项中选择`网页/全部`, 
![image](https://github.com/user-attachments/assets/b2831a9a-d394-4dbc-bb17-d6cb73489d11)
然后在保存位置的 `..._files/` 文件夹下可以看到全部的资源, 包括成就图像, 将其复制出来即可.
![image](https://github.com/user-attachments/assets/c579212e-da75-4e84-be88-8aad2de6c3bc)

**Comment by actforjason** [comment]
`download_achievements.py`很好用！
不过程序运行后有错误提示，应该是缺少`Setting.get_achievement_data_path "C:\\Users\\Jason\\AppData\\Roaming/Goldberg SteamEmu Saves/2515020/achievements.json"`，但这个和`Setting.get_achievement_json_path "steam_settings/achievements.json"`好像不一样，这个achievement data文件是怎么来的呢？

> thread 'main' panicked at src\achievement.rs:57:54:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "系统找不到指定的
文件。" }

**Comment by actforjason** [comment]
新建了一个空文件，输入大括号，不加内容可以运行了，我试试可不可以弹成就提示

**Comment by actforjason** [comment]
已成功，触发一次成就后会自动生成内容覆盖空文件
